apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "RepoUniqueNormalisedIdentifier.fullname" . }}
  labels:
    {{- include "RepoUniqueNormalisedIdentifier.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy: 
    type: {{ .Values.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "RepoUniqueNormalisedIdentifier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ now | date "2006-01-02 15:04:05" }}"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "RepoUniqueNormalisedIdentifier.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "RepoUniqueNormalisedIdentifier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.secretProviderClass.enabled }}
          volumeMounts:
            {{ range $k, $v := .Values.volumeMounts }}
            - name: {{ $v.name | quote }}
              mountPath: {{ $v.mountPath | quote }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:          
            {{ range $k, $v := .Values.env }}
            - name: {{ $v.name | quote }}
              value: {{ $v.value | quote }}
            {{- end }}
            {{ range $k, $v := .Values.global.envValuesFrom }}
            - name: {{ $v | quote }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $v | quote }}
            {{- end }}
      
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.secretProviderClass.enabled }}
      volumes:
        {{ range $k, $v := .Values.volumes }}
        - name: {{ $v.name | quote }}
          {{ if $v.secretRef }}
          secret:
            secretName: {{ $v.secretRef | quote }}   
          {{- end }}    
          {{ if $v.csiSecretProviderClass }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes: 
              secretProviderClass: {{ $v.csiSecretProviderClass }}  
          {{- end }}  
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "RepoUniqueNormalisedIdentifier.selectorLabels" . | nindent 14 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
