replicaCount: 1
deploymentStrategy: RollingUpdate

image:
  repository: pellerex/RepoUniqueNormalisedIdentifier
  pullPolicy: Always
  tag: "v1.0.0"
env:
  - name: "ASPNETCORE_ENVIRONMENT"
    value: "QualityAssurance"
  - name: "ContainerMode"
    value: "true"
  - name: "Monitoring__AzureApplicationConnectionString"
    value: "<azure-app-insights-connection-string-in-qualityassurance>"
  - name: "Monitoring__AzureApplicationInsightsInstrumentationKey"
    value: "<azure-app-insights-instrumentation-key-in-qualityassurance>"

global:
  envValuesFrom:
    Runtime__IpAddress: status.podIP

secretProviderClass:
  enabled: <secret-provider-class-enabled>

volumes:
  - name: RepoUniqueNormalisedIdentifier-api-keyvault-volume
    csiSecretProviderClass: RepoUniqueNormalisedIdentifier-api-vault

volumeMounts:
  - name: RepoUniqueNormalisedIdentifier-api-keyvault-volume
    readOnly: true
    mountPath: /root/.microsoft/usersecrets

imagePullSecrets:
  - name: image-pull-secret
nameOverride: ""
fullnameOverride: "<managed-service-name>"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: <port-number>

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
